esphome:
  name: pool-8266

esp8266:
  board: huzzah

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: ""

ota:
  password: ""

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_pass

captive_portal:

# Dallas 1-wire bus
dallas:
  - pin: 2

# Individual sensors
sensor:
  - platform: dallas
    address: 0x6f00000f057d5028
    name: "Water Temperature"

  - platform: dallas
    address: 0x7400000f05586428
    name: "Air Temperature"

  - platform: adc
    name: "Battery Voltage"
    pin: A0
    update_interval: 60s
    filters:
      - calibrate_linear:
          # Map 0.0 (from sensor) to 0.0 (true value)
          - 0.0 -> 0.0
          - 0.68 -> 3.7

binary_sensor:
  - platform: gpio
    name: "Battery Charging"
    pin:
      number: 12
      inverted: true
    filters:
      - delayed_on_off: 1s

  - platform: gpio
    name: "Input Voltage Good"
    pin:
      number: 14
      inverted: true
    filters:
      - delayed_on_off: 1s
