esphome:
  name: pool-8266
  # Make sure we don't immediately go back into deep sleep after waking
  on_boot:
    - deep_sleep.prevent: nap

esp8266:
  board: huzzah

# Enable logging
logger:

deep_sleep:
  id: nap
  run_duration: 15s
  sleep_duration: 40 s

mqtt:
  broker: 192.168.86.250
  log_topic: pool-8266/log

ota:
  password: ""

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_pass
  fast_connect: true
  power_save_mode: LIGHT

captive_portal:

# Dallas 1-wire bus
dallas:
  - pin: 2

# Individual sensors
sensor:
  - platform: dallas
    address: 0x6f00000f057d5028
    name: "Water Temperature"
    unit_of_measurement: "°C"
    icon: "mdi:pool-thermometer"

  - platform: dallas
    address: 0x7400000f05586428
    name: "Air Temperature"
    unit_of_measurement: "°C"
    icon: "mdi:sun-thermometer"

  - platform: adc
    id: battery_voltage
    name: "Battery Voltage"
    icon: "mdi:battery-50"
    unit_of_measurement: "V"
    pin: A0
    update_interval: 60s
    filters:
      - calibrate_linear:
          # Map 0.0 (from sensor) to 0.0 (true value)
          - 0.0 -> 0.0
          - 0.68 -> 3.7
    on_value_range:
      - below: 3.0
        then:
          - logger.log: "Low Battery"
          - output.set_level:
              id: blue_led
              level: 20%
      - above: 3.0
        below: 3.7
        then:
          - logger.log: "Battery Normal"
          - output.turn_off: red_led
          - output.set_level:
              id: blue_led
              level: 50%
      - above: 4.0
        then:
          - logger.log: "Battery Charging"
          - output.turn_on: red_led


binary_sensor:
  - platform: gpio
    name: "Battery Charging"
    pin:
      number: 12
      inverted: true
    filters:
      - delayed_on_off: 1s
    icon: "mdi:battery-charging"

  - platform: gpio
    name: "Input Voltage Good"
    pin:
      number: 14
      inverted: true
    filters:
      - delayed_on_off: 1s
    icon: "mdi:solar-power-variant"

text_sensor:
  - platform: mqtt_subscribe
    id: prevent_deep_sleep
    topic: homeassistant/input_boolean/prevent_deep_sleep/state

  - platform: template
    name: "Somnolence"
    id: somnolence
    icon: "mdi:sleep"
    retain: true

output:
  - id: red_led
    platform: esp8266_pwm
    pin: GPIO0
    inverted: True

  - id: blue_led
    platform: esp8266_pwm
    pin: GPIO2
    inverted: True

interval:
  - interval: 15s
    then:
      - output.turn_on: blue_led
      - delay: .5s
      - output.turn_off: blue_led
      - logger.log: 
          format: "Considering nap: MQTT %d, Prevent %s, %.2fV"
          args: [ 'mqtt_mqttclientcomponent->is_connected()', 'id(prevent_deep_sleep).state.c_str()', 'id(battery_voltage).state' ]
      - if:
          condition:
            and:
              - mqtt.connected:
              - text_sensor.state:
                  id: prevent_deep_sleep
                  state: "off"
          else:
            - text_sensor.template.publish:
                id: somnolence
                state: "Awake"
            - deep_sleep.prevent: nap
          then:
            if:
              condition:
                - sensor.in_range:
                    id: battery_voltage
                    above: 3.7
              then:
                - text_sensor.template.publish:
                    id: somnolence
                    state: "Short"
                - delay: 1s
                - deep_sleep.enter:
                    id: nap
                    sleep_duration: 44s
              else:
                - text_sensor.template.publish:
                    id: somnolence
                    state: "Long"
                - delay: 1s
                - deep_sleep.enter:
                    id: nap
                    sleep_duration: 284s